### ISSUE TITLE
About training details.

### ISSUE THREAD

**Issue by ZhongYingMatrix** [jia2lin3yuan1/2020-instanceSeg#1]
Hello, thx for ur wonderful work~
After reading ur paper, I cannot figure out the details of training DVIS, such as batchsize, step, epoch, optimizer, lr and so on.
It would be helpful if the information is available.
Appreciating your reply~

**Comment by jia2lin3yuan1** [comment]
Thank you for your interest on our work.  I am rearrange the code for releasing, will upload it once done.

For your questions, it is trained on V100 GPU, and batch size is 12 on pascal and 8 for coco-700, optimizer is SGD, lr is initialized to 1e-4 and reduced by 0.1x almost each 20 epochs.

Thanks,
Jialin


On Nov 2, 2020, at 11:34 PM, ZhongYingMatrix <notifications@github.com> wrote:

﻿

Hello, thx for ur wonderful work~
After reading ur paper, I cannot figure out the details of training DVIS, such as batchsize, step, epoch, optimizer, lr and so on.
It would be helpful if the information is available.
Appreciating your reply~

**Comment by ZhongYingMatrix** [comment]
Thx a lot~
